-- =====================================================
-- Glourant DB v1.1 - phpMyAdmin compatible
-- IMPORTANTE:
--   1) Crea/selecciona primero la base de datos en phpMyAdmin.
--   2) Luego importa este script dentro de esa base seleccionada.
--   3) Esta versión NO usa CREATE SCHEMA, NO usa USE y NO usa INDEX VISIBLE.
-- =====================================================

SET NAMES utf8mb4;

-- MySQL Script generated by MySQL Workbench
-- Mon May 11 2026 - Glourant DB v1.1
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema glourant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema glourant
-- -----------------------------------------------------

-- =====================================================
-- Glourant DB v1.1
-- Script completo para crear la base transaccional MySQL
-- y aplicar las mejoras necesarias para la demo QR en local.
--
-- Recomendado para desarrollo:
--   1) crear una base vacía,
--   2) importar este archivo completo,
--   3) usar MySQL como fuente de verdad,
--   4) proyectar tiempo real a Firestore y snapshots a MongoDB.
--
-- Si necesitas recrear todo desde cero, ejecuta manualmente antes:
-- DROP SCHEMA IF EXISTS `glourant`;
-- =====================================================
CREATE DATABASE IF NOT EXISTS `glourant`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `glourant`;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(190) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `hash_password` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `apellidos` VARCHAR(180) NULL DEFAULT NULL,
  `tipo` ENUM('cliente', 'empleado', 'propietario', 'admin_plataforma') NOT NULL DEFAULT 'cliente',
  `estado` ENUM('activo', 'bloqueado', 'baja') NOT NULL DEFAULT 'activo',
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_ultimo_acceso` DATETIME NULL DEFAULT NULL,
  `preferencia_idioma` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_usuario_email` (`email` ASC),
  INDEX `ix_usuario_telefono` (`telefono` ASC),
  INDEX `ix_usuario_tipo` (`tipo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rol` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_rol_nombre` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(160) NOT NULL,
  `nif` VARCHAR(15) NULL DEFAULT NULL,
  `email_contacto` VARCHAR(190) NULL DEFAULT NULL,
  `telefono_contacto` VARCHAR(20) NULL DEFAULT NULL,
  `estado` ENUM('activo', 'pausado', 'baja') NOT NULL DEFAULT 'activo',
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_restaurante_estado` (`estado` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `local` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `nombre_fantasia` VARCHAR(160) NOT NULL,
  `direccion` VARCHAR(240) NOT NULL,
  `municipio` VARCHAR(120) NOT NULL,
  `provincia` VARCHAR(120) NOT NULL,
  `cp` VARCHAR(10) NOT NULL,
  `latitud` DECIMAL(9,6) NULL DEFAULT NULL,
  `longitud` DECIMAL(9,6) NULL DEFAULT NULL,
  `aforo` INT NOT NULL DEFAULT 0,
  `estado` ENUM('abierto', 'cerrado', 'reforma') NOT NULL DEFAULT 'abierto',
  PRIMARY KEY (`id`),
  INDEX `ix_local_restaurante` (`restaurante_id` ASC),
  INDEX `ix_local_geo` (`latitud` ASC, `longitud` ASC),
  CONSTRAINT `fk_local_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sala` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `tipo` ENUM('interior', 'terraza', 'privado', 'barra') NOT NULL DEFAULT 'interior',
  `orden` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `ix_sala_local` (`local_id` ASC),
  CONSTRAINT `fk_sala_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mesa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sala_id` INT UNSIGNED NOT NULL,
  `codigo` VARCHAR(30) NOT NULL,
  `capacidad` INT NOT NULL,
  `estado` ENUM('libre', 'reservada', 'ocupada', 'bloqueada') NOT NULL DEFAULT 'libre',
  `qr_uuid` CHAR(36) NOT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_mesa_qr` (`qr_uuid` ASC),
  UNIQUE INDEX `ux_mesa_codigo_por_sala` (`sala_id` ASC, `codigo` ASC),
  INDEX `ix_mesa_estado` (`estado` ASC),
  CONSTRAINT `fk_mesa_sala`
    FOREIGN KEY (`sala_id`)
    REFERENCES `sala` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario_rol` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `rol_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_usuario_rol` (`usuario_id` ASC, `restaurante_id` ASC, `rol_id` ASC),
  INDEX `ix_usuario_rol_restaurante` (`restaurante_id` ASC),
  INDEX `ix_usuario_rol_rol` (`rol_id` ASC),
  CONSTRAINT `fk_urole_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_urole_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_urole_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rol` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sesion_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesion_usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `plataforma` ENUM('web', 'android', 'ios', 'tablet') NOT NULL DEFAULT 'web',
  `dispositivo_id` INT UNSIGNED NULL DEFAULT NULL,
  `inicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fin` DATETIME NULL DEFAULT NULL,
  `estado` ENUM('activa', 'cerrada', 'expirada') NOT NULL DEFAULT 'activa',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_sesion_token` (`token` ASC),
  INDEX `ix_sesion_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_sesion_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `categoria_plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria_plato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `orden` INT NOT NULL DEFAULT 0,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_categoria_restaurante` (`restaurante_id` ASC),
  CONSTRAINT `fk_categoria_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `alergeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alergeno` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `icono` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_alergeno_nombre` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `impuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuesto` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `porcentaje` DECIMAL(5,2) NOT NULL,
  `por_defecto` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_impuesto_nombre` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ingrediente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(160) NOT NULL,
  `unidad_compra` VARCHAR(20) NOT NULL,
  `unidad_consumo` VARCHAR(20) NOT NULL,
  `factor_conversion` DECIMAL(10,4) NOT NULL DEFAULT 1.0000,
  `stock_minimo` DECIMAL(12,3) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_ingrediente_restaurante` (`restaurante_id` ASC),
  CONSTRAINT `fk_ingrediente_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `preparacion_estimada_min` INT NOT NULL DEFAULT 10,
  `sku` VARCHAR(50) NULL DEFAULT NULL,
  `imagen_url` VARCHAR(255) NULL DEFAULT NULL,
  `estado` ENUM('visible', 'oculto', 'agotado') NOT NULL DEFAULT 'visible',
  `precio_base` DECIMAL(10,2) NOT NULL,
  `impuesto_id` INT UNSIGNED NOT NULL,
  `solo_en_sitio` TINYINT(1) NOT NULL DEFAULT 1,
  `permite_variantes` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `ix_plato_restaurante` (`restaurante_id` ASC),
  INDEX `ix_plato_categoria` (`categoria_id` ASC),
  INDEX `ix_plato_estado` (`estado` ASC),
  INDEX `fk_plato_impuesto` (`impuesto_id` ASC),
  CONSTRAINT `fk_plato_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plato_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria_plato` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plato_impuesto`
    FOREIGN KEY (`impuesto_id`)
    REFERENCES `impuesto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `plato_alergeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plato_alergeno` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plato_id` INT UNSIGNED NOT NULL,
  `alergeno_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_plato_alergeno` (`plato_id` ASC, `alergeno_id` ASC),
  INDEX `ix_pa_alergeno` (`alergeno_id` ASC),
  CONSTRAINT `fk_pa_plato`
    FOREIGN KEY (`plato_id`)
    REFERENCES `plato` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pa_alergeno`
    FOREIGN KEY (`alergeno_id`)
    REFERENCES `alergeno` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `variacion_plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `variacion_plato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plato_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `precio_delta` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `sku` VARCHAR(50) NULL DEFAULT NULL,
  `orden` INT NOT NULL DEFAULT 0,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_variacion_plato` (`plato_id` ASC),
  CONSTRAINT `fk_variacion_plato`
    FOREIGN KEY (`plato_id`)
    REFERENCES `plato` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `extra_opcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `extra_opcion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `max_por_plato` INT NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_extra_restaurante` (`restaurante_id` ASC),
  CONSTRAINT `fk_extra_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `plato_extra_opcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plato_extra_opcion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plato_id` INT UNSIGNED NOT NULL,
  `extra_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_plato_extra` (`plato_id` ASC, `extra_id` ASC),
  INDEX `ix_peo_extra` (`extra_id` ASC),
  CONSTRAINT `fk_peo_plato`
    FOREIGN KEY (`plato_id`)
    REFERENCES `plato` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_peo_extra`
    FOREIGN KEY (`extra_id`)
    REFERENCES `extra_opcion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plato_id` INT UNSIGNED NOT NULL,
  `ingrediente_id` INT UNSIGNED NOT NULL,
  `cantidad` DECIMAL(10,3) NOT NULL,
  `unidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_receta_plato_ingrediente` (`plato_id` ASC, `ingrediente_id` ASC),
  INDEX `ix_receta_ingrediente` (`ingrediente_id` ASC),
  CONSTRAINT `fk_receta_plato`
    FOREIGN KEY (`plato_id`)
    REFERENCES `plato` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_receta_ingrediente`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `ingrediente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacen` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_almacen_local` (`local_id` ASC),
  CONSTRAINT `fk_almacen_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `almacen_id` INT UNSIGNED NOT NULL,
  `ingrediente_id` INT UNSIGNED NOT NULL,
  `cantidad_disponible` DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  `cantidad_reservada` DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_stock_almacen_ingrediente` (`almacen_id` ASC, `ingrediente_id` ASC),
  INDEX `ix_stock_ingrediente` (`ingrediente_id` ASC),
  CONSTRAINT `fk_stock_almacen`
    FOREIGN KEY (`almacen_id`)
    REFERENCES `almacen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_ingrediente`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `ingrediente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `movimiento_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movimiento_stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `almacen_id` INT UNSIGNED NOT NULL,
  `ingrediente_id` INT UNSIGNED NOT NULL,
  `tipo` ENUM('compra', 'consumo_receta', 'ajuste', 'merma', 'devolucion_proveedor') NOT NULL,
  `cantidad` DECIMAL(12,3) NOT NULL,
  `unidad` VARCHAR(20) NOT NULL,
  `referencia` VARCHAR(120) NULL DEFAULT NULL,
  `usuario_id` INT UNSIGNED NULL DEFAULT NULL,
  `usuario_nombre_snapshot` VARCHAR(180) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_mov_stock_almacen` (`almacen_id` ASC),
  INDEX `ix_mov_stock_ingrediente` (`ingrediente_id` ASC),
  INDEX `ix_mov_stock_usuario` (`usuario_id` ASC),
  INDEX `ix_mov_stock_tipo_fecha` (`tipo` ASC, `fecha` ASC),
  CONSTRAINT `fk_ms_almacen`
    FOREIGN KEY (`almacen_id`)
    REFERENCES `almacen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ms_ingrediente`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `ingrediente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ms_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(160) NOT NULL,
  `nif` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(190) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(240) NULL DEFAULT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_proveedor_restaurante` (`restaurante_id` ASC),
  CONSTRAINT `fk_proveedor_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orden_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orden_compra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `almacen_id` INT UNSIGNED NOT NULL,
  `proveedor_id` INT UNSIGNED NOT NULL,
  `fecha_emision` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('borrador', 'enviado', 'recibido_parcial', 'recibido_completo', 'cancelado') NOT NULL DEFAULT 'borrador',
  `importe_bruto` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `impuestos` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `importe_total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  INDEX `ix_oc_almacen` (`almacen_id` ASC),
  INDEX `ix_oc_proveedor` (`proveedor_id` ASC),
  CONSTRAINT `fk_oc_almacen`
    FOREIGN KEY (`almacen_id`)
    REFERENCES `almacen` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oc_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `proveedor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `orden_compra_linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orden_compra_linea` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `orden_compra_id` INT UNSIGNED NOT NULL,
  `ingrediente_id` INT UNSIGNED NOT NULL,
  `cantidad_pedida` DECIMAL(12,3) NOT NULL,
  `unidad` VARCHAR(20) NOT NULL,
  `precio_unitario` DECIMAL(12,4) NOT NULL,
  `cantidad_recibida` DECIMAL(12,3) NOT NULL DEFAULT 0.000,
  PRIMARY KEY (`id`),
  INDEX `ix_ocl_oc` (`orden_compra_id` ASC),
  INDEX `ix_ocl_ingrediente` (`ingrediente_id` ASC),
  CONSTRAINT `fk_ocl_oc`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `orden_compra` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ocl_ingrediente`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `ingrediente` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `alias_publico` VARCHAR(60) NULL DEFAULT NULL,
  `preferencias` JSON NULL DEFAULT NULL,
  `alergenos_evitar` TEXT NULL DEFAULT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_cliente_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `favorito_restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `favorito_restaurante` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente_id` INT UNSIGNED NOT NULL,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_fav_cliente_restaurante` (`cliente_id` ASC, `restaurante_id` ASC),
  INDEX `ix_fav_restaurante` (`restaurante_id` ASC),
  CONSTRAINT `fk_fav_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fav_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `metodo_pago_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodo_pago_cliente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente_id` INT UNSIGNED NOT NULL,
  `proveedor_pago` ENUM('stripe', 'redsys', 'bizum', 'otros') NOT NULL,
  `token` VARCHAR(190) NOT NULL,
  `marca` VARCHAR(30) NULL DEFAULT NULL,
  `ultimos4` CHAR(4) NULL DEFAULT NULL,
  `expira_mes` TINYINT NULL DEFAULT NULL,
  `expira_anio` SMALLINT NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_mpc_cliente` (`cliente_id` ASC),
  CONSTRAINT `fk_mpc_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NULL DEFAULT NULL,
  `personas` INT NOT NULL,
  `fecha_reserva` DATE NOT NULL,
  `hora_reserva` TIME NOT NULL,
  `estado` ENUM('pendiente_confirmar', 'confirmada', 'en_curso', 'no_presentado', 'cancelada', 'finalizada') NOT NULL DEFAULT 'pendiente_confirmar',
  `preferencia_sala` ENUM('cualquiera', 'interior', 'terraza', 'privado') NOT NULL DEFAULT 'cualquiera',
  `notas` TEXT NULL DEFAULT NULL,
  `creada_por_usuario_id` INT UNSIGNED NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_reserva_local_fecha` (`local_id` ASC, `fecha_reserva` ASC),
  INDEX `ix_reserva_cliente` (`cliente_id` ASC),
  INDEX `fk_reserva_creador` (`creada_por_usuario_id` ASC),
  CONSTRAINT `fk_reserva_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reserva_creador`
    FOREIGN KEY (`creada_por_usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `reserva_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reserva_mesa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reserva_id` INT UNSIGNED NOT NULL,
  `mesa_id` INT UNSIGNED NOT NULL,
  `desde` DATETIME NOT NULL,
  `hasta` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_reserva_mesa_intervalo` (`reserva_id` ASC, `mesa_id` ASC, `desde` ASC),
  INDEX `ix_rm_mesa` (`mesa_id` ASC),
  CONSTRAINT `fk_rm_reserva`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `reserva` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rm_mesa`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mesa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `penalizacion_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penalizacion_reserva` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente_id` INT UNSIGNED NOT NULL,
  `reserva_id` INT UNSIGNED NOT NULL,
  `motivo` ENUM('no_presentado', 'cancelacion_tardia', 'otro') NOT NULL,
  `puntos` INT NOT NULL DEFAULT 1,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_pr_cliente` (`cliente_id` ASC),
  INDEX `ix_pr_reserva` (`reserva_id` ASC),
  CONSTRAINT `fk_pr_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pr_reserva`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `reserva` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lista_espera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lista_espera` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NULL DEFAULT NULL,
  `personas` INT NOT NULL,
  `prioridad` INT NOT NULL DEFAULT 0,
  `estado` ENUM('en_espera', 'avisado', 'caducado', 'cancelado') NOT NULL DEFAULT 'en_espera',
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_le_local` (`local_id` ASC),
  INDEX `ix_le_cliente` (`cliente_id` ASC),
  CONSTRAINT `fk_le_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_le_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comanda` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `local_id` INT UNSIGNED NOT NULL,
  `mesa_id` INT UNSIGNED NULL DEFAULT NULL,
  `reserva_id` INT UNSIGNED NULL DEFAULT NULL,
  `cliente_id` INT UNSIGNED NULL DEFAULT NULL,
  `canal` ENUM('mesa_qr', 'reserva', 'staff_tablet') NOT NULL,
  `estado` ENUM('abierta', 'en_preparacion', 'servida_parcial', 'servida_total', 'cerrada', 'anulada') NOT NULL DEFAULT 'abierta',
  `origen` ENUM('cliente_app', 'camarero', 'jefe_sala') NOT NULL,
  `importe_bruto` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `impuestos` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `descuentos` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `importe_total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `propina` DECIMAL(10,2) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_cierre` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_comanda_restaurante` (`restaurante_id` ASC),
  INDEX `ix_comanda_local` (`local_id` ASC),
  INDEX `ix_comanda_mesa` (`mesa_id` ASC),
  INDEX `ix_comanda_reserva` (`reserva_id` ASC),
  INDEX `ix_comanda_cliente` (`cliente_id` ASC),
  INDEX `ix_comanda_estado` (`estado` ASC),
  CONSTRAINT `fk_comanda_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_mesa`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mesa` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_reserva`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `reserva` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comanda_linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comanda_linea` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_id` INT UNSIGNED NOT NULL,
  `plato_id` INT UNSIGNED NOT NULL,
  `variacion_id` INT UNSIGNED NULL DEFAULT NULL,
  `nombre_plato_snapshot` VARCHAR(200) NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT 1.00,
  `impuesto_porcentaje` DECIMAL(5,2) NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'en_cocina', 'listo', 'servido', 'anulado') NOT NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id`),
  INDEX `ix_cl_comanda` (`comanda_id` ASC),
  INDEX `ix_cl_plato` (`plato_id` ASC),
  INDEX `ix_cl_variacion` (`variacion_id` ASC),
  CONSTRAINT `fk_cl_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cl_plato`
    FOREIGN KEY (`plato_id`)
    REFERENCES `plato` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cl_variacion`
    FOREIGN KEY (`variacion_id`)
    REFERENCES `variacion_plato` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comanda_linea_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comanda_linea_extra` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_linea_id` INT UNSIGNED NOT NULL,
  `extra_id` INT UNSIGNED NOT NULL,
  `nombre_extra_snapshot` VARCHAR(160) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  INDEX `ix_cle_linea` (`comanda_linea_id` ASC),
  INDEX `ix_cle_extra` (`extra_id` ASC),
  CONSTRAINT `fk_cle_linea`
    FOREIGN KEY (`comanda_linea_id`)
    REFERENCES `comanda_linea` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cle_extra`
    FOREIGN KEY (`extra_id`)
    REFERENCES `extra_opcion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pase_cocina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pase_cocina` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_id` INT UNSIGNED NOT NULL,
  `numero` INT NOT NULL,
  `estado` ENUM('pendiente', 'en_preparacion', 'listo', 'entregado_sala', 'cancelado') NOT NULL DEFAULT 'pendiente',
  `nota_cocina` TEXT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_cierre` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_pase_por_comanda` (`comanda_id` ASC, `numero` ASC),
  CONSTRAINT `fk_pase_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pase_cocina_linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pase_cocina_linea` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pase_id` INT UNSIGNED NOT NULL,
  `comanda_linea_id` INT UNSIGNED NOT NULL,
  `partida` ENUM('frio', 'plancha', 'fritos', 'horno', 'postres', 'barra', 'bebidas') NOT NULL,
  `estado` ENUM('pendiente', 'en_preparacion', 'listo', 'entregado') NOT NULL DEFAULT 'pendiente',
  `tiempo_inicio` DATETIME NULL DEFAULT NULL,
  `tiempo_fin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_pcl_pase_linea` (`pase_id` ASC, `comanda_linea_id` ASC),
  INDEX `ix_pcl_linea` (`comanda_linea_id` ASC),
  CONSTRAINT `fk_pcl_pase`
    FOREIGN KEY (`pase_id`)
    REFERENCES `pase_cocina` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pcl_linea`
    FOREIGN KEY (`comanda_linea_id`)
    REFERENCES `comanda_linea` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `comanda_estado_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comanda_estado_historial` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_id` INT UNSIGNED NOT NULL,
  `estado` ENUM('abierta', 'en_preparacion', 'servida_parcial', 'servida_total', 'cerrada', 'anulada') NOT NULL,
  `usuario_id` INT UNSIGNED NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comentario` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_ceh_comanda` (`comanda_id` ASC),
  INDEX `ix_ceh_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_ceh_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ceh_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pago_intento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pago_intento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NULL DEFAULT NULL,
  `proveedor_pago` ENUM('stripe', 'redsys', 'bizum', 'efectivo', 'otros') NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `moneda` CHAR(3) NOT NULL DEFAULT 'EUR',
  `estado` ENUM('iniciado', 'preautorizado', 'fallido', 'cancelado', 'capturado_parcial', 'capturado_total') NOT NULL DEFAULT 'iniciado',
  `token_proveedor` VARCHAR(190) NULL DEFAULT NULL,
  `mensaje_proveedor` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_pi_comanda` (`comanda_id` ASC),
  INDEX `ix_pi_cliente` (`cliente_id` ASC),
  CONSTRAINT `fk_pi_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pi_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `pago_transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pago_transaccion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_id` INT UNSIGNED NOT NULL,
  `pago_intento_id` INT UNSIGNED NULL DEFAULT NULL,
  `tipo` ENUM('captura', 'devolucion') NOT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `proveedor_pago` ENUM('stripe', 'redsys', 'bizum', 'efectivo', 'otros') NOT NULL,
  `referencia_proveedor` VARCHAR(190) NOT NULL,
  `resultado` ENUM('ok', 'error') NOT NULL,
  `mensaje_resultado` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_pt_comanda` (`comanda_id` ASC),
  INDEX `ix_pt_intento` (`pago_intento_id` ASC),
  CONSTRAINT `fk_pt_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pt_intento`
    FOREIGN KEY (`pago_intento_id`)
    REFERENCES `pago_intento` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factura` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_id` INT UNSIGNED NOT NULL,
  `numero` VARCHAR(30) NOT NULL,
  `tipo` ENUM('simplificada', 'completa') NOT NULL DEFAULT 'simplificada',
  `razon_social` VARCHAR(180) NULL DEFAULT NULL,
  `nif` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(240) NULL DEFAULT NULL,
  `importe_bruto` DECIMAL(12,2) NOT NULL,
  `impuestos` DECIMAL(12,2) NOT NULL,
  `importe_total` DECIMAL(12,2) NOT NULL,
  `fecha_emision` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pdf_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_factura_numero` (`numero` ASC),
  INDEX `ix_factura_comanda` (`comanda_id` ASC),
  CONSTRAINT `fk_factura_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devolucion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comanda_id` INT UNSIGNED NOT NULL,
  `pago_transaccion_id` INT UNSIGNED NULL DEFAULT NULL,
  `monto` DECIMAL(12,2) NOT NULL,
  `motivo` ENUM('no_disponible', 'tiempo_excesivo', 'error_preparacion', 'otro') NOT NULL,
  `estado` ENUM('solicitada', 'aprobada', 'procesada', 'rechazada') NOT NULL DEFAULT 'solicitada',
  `fecha_solicitud` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_resolucion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_dev_comanda` (`comanda_id` ASC),
  INDEX `ix_dev_transaccion` (`pago_transaccion_id` ASC),
  CONSTRAINT `fk_dev_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dev_transaccion`
    FOREIGN KEY (`pago_transaccion_id`)
    REFERENCES `pago_transaccion` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `metodo_pago_aceptado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodo_pago_aceptado` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `local_id` INT UNSIGNED NULL DEFAULT NULL,
  `metodo` ENUM('efectivo', 'tarjeta', 'bizum', 'contactless', 'vale', 'otros') NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_mpa_restaurante` (`restaurante_id` ASC),
  INDEX `ix_mpa_local` (`local_id` ASC),
  CONSTRAINT `fk_mpa_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mpa_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `caja_cierre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caja_cierre` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `turno` ENUM('desayuno', 'comida', 'cena', 'completo') NOT NULL DEFAULT 'completo',
  `efectivo_declarado` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `tpv_total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `ajuste` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `observaciones` TEXT NULL DEFAULT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `fecha_cierre` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_caja_local_fecha_turno` (`local_id` ASC, `fecha` ASC, `turno` ASC),
  INDEX `ix_caja_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_caja_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_caja_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valoracion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `comanda_id` INT UNSIGNED NOT NULL,
  `cliente_id` INT UNSIGNED NULL DEFAULT NULL,
  `puntuacion` TINYINT NOT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `visibilidad` ENUM('privada', 'publica') NOT NULL DEFAULT 'privada',
  `moderacion` ENUM('pendiente', 'aprobada', 'rechazada') NOT NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id`),
  INDEX `ix_val_restaurante` (`restaurante_id` ASC),
  INDEX `ix_val_comanda` (`comanda_id` ASC),
  INDEX `ix_val_cliente` (`cliente_id` ASC),
  CONSTRAINT `fk_val_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_val_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_val_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificacion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `tipo` ENUM('push', 'email', 'interno') NOT NULL,
  `titulo` VARCHAR(160) NOT NULL,
  `mensaje` TEXT NOT NULL,
  `estado` ENUM('pendiente', 'enviado', 'fallido', 'leido') NOT NULL DEFAULT 'pendiente',
  `fecha_creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_envio` DATETIME NULL DEFAULT NULL,
  `referencia_tipo` ENUM('comanda', 'reserva', 'devolucion', 'otro') NOT NULL DEFAULT 'otro',
  `referencia_id` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_notif_usuario` (`usuario_id` ASC),
  INDEX `ix_notif_estado` (`estado` ASC),
  CONSTRAINT `fk_notif_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `evento_analitica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evento_analitica` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `local_id` INT UNSIGNED NULL DEFAULT NULL,
  `usuario_id` INT UNSIGNED NULL DEFAULT NULL,
  `tipo_evento` VARCHAR(60) NOT NULL,
  `payload` JSON NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_ea_restaurante` (`restaurante_id` ASC),
  INDEX `ix_ea_local` (`local_id` ASC),
  INDEX `ix_ea_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_ea_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ea_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ea_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `kpi_diario_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kpi_diario_local` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `comandas` INT NOT NULL DEFAULT 0,
  `tickets_medio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `importe_total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `personas_atendidas` INT NOT NULL DEFAULT 0,
  `tiempo_medio_preparacion_min` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  `no_shows` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_kpi_local_fecha` (`local_id` ASC, `fecha` ASC),
  CONSTRAINT `fk_kpi_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NULL DEFAULT NULL,
  `entidad` VARCHAR(50) NOT NULL,
  `entidad_id` INT UNSIGNED NOT NULL,
  `accion` ENUM('crear', 'actualizar', 'borrar', 'estado') NOT NULL,
  `detalle` JSON NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `ix_aud_usuario` (`usuario_id` ASC),
  INDEX `ix_aud_entidad` (`entidad` ASC, `entidad_id` ASC),
  CONSTRAINT `fk_aud_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `config_restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `config_restaurante` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `clave` VARCHAR(60) NOT NULL,
  `valor` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_conf_rest_clave` (`restaurante_id` ASC, `clave` ASC),
  CONSTRAINT `fk_conf_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `turno_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `turno_empleado` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` INT UNSIGNED NOT NULL,
  `local_id` INT UNSIGNED NOT NULL,
  `inicio` DATETIME NOT NULL,
  `fin` DATETIME NOT NULL,
  `rol_id` INT UNSIGNED NOT NULL,
  `estado` ENUM('planificado', 'en_curso', 'finalizado', 'ausente') NOT NULL DEFAULT 'planificado',
  PRIMARY KEY (`id`),
  INDEX `ix_turno_usuario` (`usuario_id` ASC),
  INDEX `ix_turno_local` (`local_id` ASC),
  INDEX `ix_turno_rol` (`rol_id` ASC),
  CONSTRAINT `fk_turno_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turno_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turno_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `rol` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bloqueo_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloqueo_mesa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mesa_id` INT UNSIGNED NOT NULL,
  `motivo` ENUM('limpieza', 'mantenimiento', 'incidencia', 'otros') NOT NULL,
  `desde` DATETIME NOT NULL,
  `hasta` DATETIME NULL DEFAULT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_bm_mesa` (`mesa_id` ASC),
  INDEX `ix_bm_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_bm_mesa`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mesa` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bm_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promocion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `restaurante_id` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(160) NOT NULL,
  `tipo` ENUM('porcentaje', 'importe', 'menu_dia') NOT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `vigencia_desde` DATE NOT NULL,
  `vigencia_hasta` DATE NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `ix_promo_restaurante` (`restaurante_id` ASC),
  CONSTRAINT `fk_promo_restaurante`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `restaurante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `promocion_plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `promocion_plato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `promocion_id` INT UNSIGNED NOT NULL,
  `plato_id` INT UNSIGNED NULL DEFAULT NULL,
  `categoria_id` INT UNSIGNED NULL DEFAULT NULL,
  `prioridad` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_promo_target` (`promocion_id` ASC, `plato_id` ASC, `categoria_id` ASC),
  INDEX `ix_pp_plato` (`plato_id` ASC),
  INDEX `ix_pp_categoria` (`categoria_id` ASC),
  CONSTRAINT `fk_pp_promocion`
    FOREIGN KEY (`promocion_id`)
    REFERENCES `promocion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pp_plato`
    FOREIGN KEY (`plato_id`)
    REFERENCES `plato` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pp_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `categoria_plato` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;




-- =====================================================
-- Glourant DB v1.1 - Actualizaciones estructurales
-- =====================================================

-- -----------------------------------------------------
-- Mesa: soporte específico para QR y estado cacheado.
-- -----------------------------------------------------
ALTER TABLE `mesa`
  ADD COLUMN `qr_activo` TINYINT(1) NOT NULL DEFAULT 1 AFTER `qr_uuid`,
  ADD COLUMN `permite_pedido_qr` TINYINT(1) NOT NULL DEFAULT 1 AFTER `qr_activo`,
  ADD COLUMN `estado_actualizado_at` DATETIME NULL DEFAULT NULL AFTER `permite_pedido_qr`,
  ADD INDEX `ix_mesa_qr_activo` (`qr_activo` ASC);

-- -----------------------------------------------------
-- Plato por local: permite disponibilidad/precio por sede.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plato_local` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `plato_id` INT UNSIGNED NOT NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  `estado` ENUM('visible', 'oculto', 'agotado') NOT NULL DEFAULT 'visible',
  `precio_override` DECIMAL(10,2) NULL DEFAULT NULL,
  `preparacion_estimada_min_override` INT NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_plato_local` (`local_id` ASC, `plato_id` ASC),
  INDEX `ix_plato_local_estado` (`local_id` ASC, `estado` ASC),
  CONSTRAINT `fk_pl_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pl_plato`
    FOREIGN KEY (`plato_id`)
    REFERENCES `plato` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Reservas: rango temporal real, origen y código de confirmación.
-- La prevención de solapes debe hacerse en backend con SELECT ... FOR UPDATE:
-- mesa_id = ? AND desde < nueva_hasta AND hasta > nueva_desde
-- -----------------------------------------------------
ALTER TABLE `reserva`
  ADD COLUMN `desde` DATETIME NULL DEFAULT NULL AFTER `hora_reserva`,
  ADD COLUMN `hasta` DATETIME NULL DEFAULT NULL AFTER `desde`,
  ADD COLUMN `duracion_min` INT NOT NULL DEFAULT 90 AFTER `hasta`,
  ADD COLUMN `origen` ENUM('app', 'web', 'telefono', 'staff') NOT NULL DEFAULT 'app' AFTER `preferencia_sala`,
  ADD COLUMN `codigo_confirmacion` VARCHAR(20) NULL DEFAULT NULL AFTER `origen`,
  ADD UNIQUE INDEX `ux_reserva_codigo_confirmacion` (`codigo_confirmacion` ASC),
  ADD INDEX `ix_reserva_local_desde_hasta` (`local_id` ASC, `desde` ASC, `hasta` ASC);

ALTER TABLE `reserva_mesa`
  ADD INDEX `ix_rm_mesa_desde_hasta` (`mesa_id` ASC, `desde` ASC, `hasta` ASC);

-- -----------------------------------------------------
-- Sesión de mesa: pieza central del flujo QR/demostración en vivo.
-- Permite cliente anónimo, pedido por token, vinculación posterior a usuario
-- y control de ocupación sin depender solo de mesa.estado.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesion_mesa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `local_id` INT UNSIGNED NOT NULL,
  `mesa_id` INT UNSIGNED NOT NULL,
  `reserva_id` INT UNSIGNED NULL DEFAULT NULL,
  `cliente_id` INT UNSIGNED NULL DEFAULT NULL,
  `token_uuid` CHAR(36) NOT NULL,
  `personas` INT NULL DEFAULT NULL,
  `estado` ENUM('activa', 'pidiendo', 'en_preparacion', 'solicitando_pago', 'pagada', 'cerrada', 'cancelada') NOT NULL DEFAULT 'activa',
  `fecha_inicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `origen` ENUM('qr', 'reserva', 'staff') NOT NULL DEFAULT 'qr',
  `notas` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ux_sesion_mesa_token` (`token_uuid` ASC),
  INDEX `ix_sesion_mesa_local_estado` (`local_id` ASC, `estado` ASC),
  INDEX `ix_sesion_mesa_mesa_estado` (`mesa_id` ASC, `estado` ASC),
  INDEX `ix_sesion_mesa_cliente` (`cliente_id` ASC),
  CONSTRAINT `fk_sm_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sm_mesa`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mesa` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sm_reserva`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `reserva` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sm_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cliente` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Comanda: vínculo con sesión de mesa y estados de pago.
-- -----------------------------------------------------
ALTER TABLE `comanda`
  ADD COLUMN `sesion_mesa_id` INT UNSIGNED NULL DEFAULT NULL AFTER `cliente_id`,
  MODIFY COLUMN `estado` ENUM('abierta', 'en_preparacion', 'servida_parcial', 'servida_total', 'solicitando_pago', 'pagada', 'cerrada', 'anulada') NOT NULL DEFAULT 'abierta',
  MODIFY COLUMN `origen` ENUM('cliente_app', 'cliente_qr', 'camarero', 'jefe_sala') NOT NULL,
  ADD COLUMN `fecha_actualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `fecha_creacion`,
  ADD INDEX `ix_comanda_sesion_mesa` (`sesion_mesa_id` ASC),
  ADD INDEX `ix_comanda_local_estado_fecha` (`local_id` ASC, `estado` ASC, `fecha_creacion` ASC),
  ADD CONSTRAINT `fk_comanda_sesion_mesa`
    FOREIGN KEY (`sesion_mesa_id`)
    REFERENCES `sesion_mesa` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

-- -----------------------------------------------------
-- Líneas de comanda: snapshots completos y trazabilidad de cocina/sala.
-- -----------------------------------------------------
ALTER TABLE `comanda_linea`
  ADD COLUMN `nombre_variacion_snapshot` VARCHAR(120) NULL DEFAULT NULL AFTER `nombre_plato_snapshot`,
  ADD COLUMN `precio_variacion_delta` DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER `precio_unitario`,
  ADD COLUMN `subtotal_linea` DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER `cantidad`,
  ADD COLUMN `impuesto_monto` DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER `impuesto_porcentaje`,
  ADD COLUMN `total_linea` DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER `impuesto_monto`,
  ADD COLUMN `fecha_estado` DATETIME NULL DEFAULT NULL AFTER `estado`,
  ADD COLUMN `enviado_cocina_at` DATETIME NULL DEFAULT NULL AFTER `fecha_estado`,
  ADD COLUMN `listo_at` DATETIME NULL DEFAULT NULL AFTER `enviado_cocina_at`,
  ADD COLUMN `servido_at` DATETIME NULL DEFAULT NULL AFTER `listo_at`,
  ADD INDEX `ix_cl_estado` (`estado` ASC);

ALTER TABLE `comanda_linea_extra`
  ADD COLUMN `cantidad` DECIMAL(10,2) NOT NULL DEFAULT 1.00 AFTER `nombre_extra_snapshot`,
  ADD COLUMN `precio_unitario` DECIMAL(10,2) NOT NULL DEFAULT 0.00 AFTER `cantidad`;

-- -----------------------------------------------------
-- Cocina: acceso directo por local para panel en vivo.
-- -----------------------------------------------------
ALTER TABLE `pase_cocina`
  ADD COLUMN `local_id` INT UNSIGNED NOT NULL AFTER `comanda_id`,
  ADD INDEX `ix_pase_local_estado` (`local_id` ASC, `estado` ASC),
  ADD CONSTRAINT `fk_pase_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- -----------------------------------------------------
-- Pagos: idempotencia, referencias externas, metadata y estados ampliados.
-- -----------------------------------------------------
ALTER TABLE `pago_intento`
  ADD COLUMN `idempotency_key` VARCHAR(100) NULL DEFAULT NULL AFTER `proveedor_pago`,
  MODIFY COLUMN `estado` ENUM('iniciado', 'pendiente', 'preautorizado', 'autorizado', 'fallido', 'cancelado', 'capturado_parcial', 'capturado_total', 'devuelto_parcial', 'devuelto_total') NOT NULL DEFAULT 'iniciado',
  ADD COLUMN `referencia_proveedor` VARCHAR(190) NULL DEFAULT NULL AFTER `token_proveedor`,
  ADD COLUMN `metadata` JSON NULL DEFAULT NULL AFTER `mensaje_proveedor`,
  ADD UNIQUE INDEX `ux_pi_idempotency` (`idempotency_key` ASC),
  ADD INDEX `ix_pi_proveedor_ref` (`proveedor_pago` ASC, `referencia_proveedor` ASC);

ALTER TABLE `pago_transaccion`
  MODIFY COLUMN `referencia_proveedor` VARCHAR(190) NULL DEFAULT NULL,
  ADD COLUMN `metadata` JSON NULL DEFAULT NULL AFTER `mensaje_resultado`,
  ADD INDEX `ix_pt_proveedor_ref` (`proveedor_pago` ASC, `referencia_proveedor` ASC);

-- -----------------------------------------------------
-- Facturación: serie/local/ejercicio para numeración fiscal por sede.
-- -----------------------------------------------------
ALTER TABLE `factura`
  ADD COLUMN `local_id` INT UNSIGNED NOT NULL AFTER `comanda_id`,
  ADD COLUMN `serie` VARCHAR(20) NOT NULL DEFAULT 'A' AFTER `local_id`,
  ADD COLUMN `ejercicio` SMALLINT UNSIGNED NOT NULL AFTER `serie`,
  ADD COLUMN `numero_secuencial` INT UNSIGNED NOT NULL AFTER `ejercicio`,
  ADD UNIQUE INDEX `ux_factura_local_serie_numero` (`local_id` ASC, `ejercicio` ASC, `serie` ASC, `numero_secuencial` ASC),
  ADD INDEX `ix_factura_local_fecha` (`local_id` ASC, `fecha_emision` ASC),
  ADD CONSTRAINT `fk_factura_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `local` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

-- -----------------------------------------------------
-- Notificaciones: se añade sesion_mesa como entidad notificable.
-- -----------------------------------------------------
ALTER TABLE `notificacion`
  MODIFY COLUMN `referencia_tipo` ENUM('comanda', 'reserva', 'sesion_mesa', 'devolucion', 'otro') NOT NULL DEFAULT 'otro';

-- -----------------------------------------------------
-- Outbox de sincronización: proyección segura a Firestore/MongoDB.
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sync_outbox` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aggregate_type` VARCHAR(60) NOT NULL,
  `aggregate_id` BIGINT UNSIGNED NOT NULL,
  `event_type` VARCHAR(80) NOT NULL,
  `payload` JSON NOT NULL,
  `estado` ENUM('pendiente', 'procesando', 'procesado', 'error') NOT NULL DEFAULT 'pendiente',
  `intentos` INT NOT NULL DEFAULT 0,
  `error_mensaje` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ix_outbox_estado_created` (`estado` ASC, `created_at` ASC),
  INDEX `ix_outbox_aggregate` (`aggregate_type` ASC, `aggregate_id` ASC),
  INDEX `ix_outbox_event_type` (`event_type` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

-- =====================================================
-- Fin Glourant DB v1.1
-- =====================================================

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
